export let DisciplinaValues: string[] = ['MATEMATICA', 'PORTUGUES', 'INGLES', 'GEOGRAFIA', 'HISTORIA', 'QUIMICA', 'BIOLOGIA', 'FISICA', 'SOCIOLOGIA', 'LITERATURA'];
export type Disciplina = 'MATEMATICA' | 'PORTUGUES' | 'INGLES' | 'GEOGRAFIA' | 'HISTORIA' | 'QUIMICA' | 'BIOLOGIA' | 'FISICA' | 'SOCIOLOGIA' | 'LITERATURA';
